Leonhsi proposal attempt2
yungyuc/nsdhw_22sp pull request #121
Opened 2022-04-05 08:16 UTC by leonhsi

---
A good PR should include the following parts:

- [ ] A clear title
- [ ] A meaningful message for PR, as well as its commits
- [ ] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [ ] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

2022-04-05 14:03 UTC, yungyuc requested changes
Please resolve the merge conflict and add review comments to indicate where you addressed my questions made in #119.

I do not have time to compare the two PRs line by line.

2022-04-06 05:12 UTC, leonhsi commented on project/leonhsi/README.md
> +In this project, I would evaluate each trees with common scenes in computer graphics such as dragon, rabbit, etc. Each of these scenes contains millions of primitives.
My project would evaluate with common real world scenes which contain millions of primitives.

2022-04-06 05:21 UTC, leonhsi commented on project/leonhsi/README.md
> +In this project, I would evaluate each trees with common scenes in computer graphics such as dragon, rabbit, etc. Each of these scenes contains millions of primitives.
My project will be evaluate with common real world scenes which would contain millions of primitives.

2022-04-06 05:21 UTC, leonhsi commented on project/leonhsi/README.md
> +###### links: [link to github repo](https://github.com/leonhsi/BVH_Generator)
I add the link to my github repo

2022-04-06 05:21 UTC, leonhsi commented on project/leonhsi/README.md
> +* week 6 : visualize the result using charts and prepare for the presentation
I change my schedule of week 4 and 5 that I will run the test right after I finish most work in my project and make future analysis after testing.
Also I will visualize the performance using charts for the presentation.

2022-04-06 11:15 UTC, yungyuc commented on project/README.rst
> +   `BVH-Generator <README.rst>`__ : https://github.com/leonhsi/BVH_Generator
You should point to your `leonhsi/README.md`.  `README.rst` is the list itself.  It will be great if you can fix it, but I can fix it myself later.

2022-04-06 11:15 UTC, yungyuc commented on project/leonhsi/README.md
> +There will be only one API and user only need to input which kinds of BVH trees he or she wants, then the output will be the performance of this BVH tree.
A single API won't be very useful and it won't be easy to write Python unit testing.  I suggest to start to write tests early to give yourself a taste about it.

2022-04-06 11:15 UTC, yungyuc approved these changes

2022-04-06 11:15 UTC, merged

2022-04-14 13:21 UTC, yungyuc commented
You didn't add the PR link in E3.