Oscarpolai-proposal-attempt1
yungyuc/nsdhw_22sp pull request #122
Opened 2022-04-05 16:23 UTC by OscarPolai

---
A good PR should include the following parts:

- [ ] A clear title
- [ ] A meaningful message for PR, as well as its commits
- [ ] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [ ] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

2022-04-05 23:01 UTC, yungyuc requested changes
Please add an entry pointing to your `OscarPolai/Readme.md` in the `README.rst` in the upper-level directory.

The proposal is generally well thought.

2022-04-05 23:01 UTC, yungyuc commented on project/OscarPolai/Readme.md
> +1. Those who do data analysis dealing with large datasets.
It might be good for you to analyze with the comparison with other C++-based data frame library, although it's not required.

2022-04-05 23:01 UTC, yungyuc commented on project/OscarPolai/Readme.md
> +	* Analyze the memory behavior in runtime, refined the previous design.
Memory analysis is non-trivial.  It may help you to think about what tools you want to use for it.

2022-04-13 09:30 UTC, OscarPolai commented
@yungyuc I've add an entry pointing to my repo on the up-level directory. By the way, this is my first time to resolve conflict...

2022-04-14 13:03 UTC, yungyuc commented
> @yungyuc I've add an entry pointing to my repo on the up-level directory. By the way, this is my first time to resolve conflict...

I am happy that you earn the first experience before you leave university.

2022-04-14 13:03 UTC, merged

2022-04-14 13:04 UTC, yungyuc commented
Merge with outstanding issues but they are minor.