simpson0114-hw0-attempt1
yungyuc/nsdhw_22sp pull request #28
Opened 2022-02-16 08:15 UTC by simpson0114

- [x] 1. Run countline.py.
---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

2022-02-16 09:48 UTC, yungyuc requested changes
You incorrectly included an unrelated change (set) https://github.com/yungyuc/nsdhw_22sp/pull/28/commits/de641f4c53763584b30a7d668ccdec9a7968598f .  Please rewrite the history (of this PR) to remove it.

2022-02-18 07:09 UTC, simpson0114 commented
Teacher, I have rewritten the history (of this PR) to remove it.

2022-02-18 23:13 UTC, yungyuc approved these changes

2022-02-18 23:13 UTC, yungyuc requested changes
You mixed hw1 with hw0 now.  One homework should use only one PR.  Please fix again.  You can choose to use this for hw0 and file another PR for hw1, or discard hw0 in this PR to repurpose it for hw1.

2022-02-19 04:41 UTC, closed without merging